set_property SRC_FILE_INFO {cfile:Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/constrs_1/new/vga_constraints.xdc rfile:../../../local_testing_vga_ip_1.srcs/constrs_1/new/vga_constraints.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/constrs_1/imports/constraints/gyro_nexys_a7.xdc rfile:../../../local_testing_vga_ip_1.srcs/constrs_1/imports/constraints/gyro_nexys_a7.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_100MHz]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports reset_rtl_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {VGA_R[0]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {VGA_R[1]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {VGA_R[2]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {VGA_R[3]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[0]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {VGA_G[1]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[2]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[3]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[0]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[1]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[2]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {VGA_B[3]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports VGA_HSYNC]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports VGA_VSYNC]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports {gpio_io_i_0[0]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {gpio_io_i_0[1]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports {gpio_io_i_0[2]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports {gpio_io_i_0[3]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_3_i/clk_100MHz_RnM/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_3_i/top_sound_0/inst/dbg_loop_arrow[0]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[1]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[2]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[3]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[4]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[5]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[6]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[7]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[8]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[9]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[10]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[11]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[12]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[13]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[14]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[15]}]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_3_i/top_sound_0/inst/dbg_sample[0]} {design_3_i/top_sound_0/inst/dbg_sample[1]} {design_3_i/top_sound_0/inst/dbg_sample[2]} {design_3_i/top_sound_0/inst/dbg_sample[3]} {design_3_i/top_sound_0/inst/dbg_sample[4]} {design_3_i/top_sound_0/inst/dbg_sample[5]} {design_3_i/top_sound_0/inst/dbg_sample[6]} {design_3_i/top_sound_0/inst/dbg_sample[7]}]]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_3_i/top_sound_0/inst/dbg_addr_arrow[0]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[1]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[2]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[3]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[4]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[5]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[6]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[7]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[8]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[9]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[10]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[11]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[12]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[13]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[14]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[15]}]]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_3_i/top_sound_0/inst/dbg_loop_menu[0]} {design_3_i/top_sound_0/inst/dbg_loop_menu[1]} {design_3_i/top_sound_0/inst/dbg_loop_menu[2]} {design_3_i/top_sound_0/inst/dbg_loop_menu[3]} {design_3_i/top_sound_0/inst/dbg_loop_menu[4]} {design_3_i/top_sound_0/inst/dbg_loop_menu[5]} {design_3_i/top_sound_0/inst/dbg_loop_menu[6]} {design_3_i/top_sound_0/inst/dbg_loop_menu[7]} {design_3_i/top_sound_0/inst/dbg_loop_menu[8]} {design_3_i/top_sound_0/inst/dbg_loop_menu[9]} {design_3_i/top_sound_0/inst/dbg_loop_menu[10]} {design_3_i/top_sound_0/inst/dbg_loop_menu[11]} {design_3_i/top_sound_0/inst/dbg_loop_menu[12]} {design_3_i/top_sound_0/inst/dbg_loop_menu[13]} {design_3_i/top_sound_0/inst/dbg_loop_menu[14]} {design_3_i/top_sound_0/inst/dbg_loop_menu[15]}]]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_3_i/top_sound_0/inst/dbg_addr_music[0]} {design_3_i/top_sound_0/inst/dbg_addr_music[1]} {design_3_i/top_sound_0/inst/dbg_addr_music[2]} {design_3_i/top_sound_0/inst/dbg_addr_music[3]} {design_3_i/top_sound_0/inst/dbg_addr_music[4]} {design_3_i/top_sound_0/inst/dbg_addr_music[5]} {design_3_i/top_sound_0/inst/dbg_addr_music[6]} {design_3_i/top_sound_0/inst/dbg_addr_music[7]} {design_3_i/top_sound_0/inst/dbg_addr_music[8]} {design_3_i/top_sound_0/inst/dbg_addr_music[9]} {design_3_i/top_sound_0/inst/dbg_addr_music[10]} {design_3_i/top_sound_0/inst/dbg_addr_music[11]} {design_3_i/top_sound_0/inst/dbg_addr_music[12]} {design_3_i/top_sound_0/inst/dbg_addr_music[13]} {design_3_i/top_sound_0/inst/dbg_addr_music[14]} {design_3_i/top_sound_0/inst/dbg_addr_music[15]}]]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_3_i/top_sound_0/inst/dbg_addr_menu[0]} {design_3_i/top_sound_0/inst/dbg_addr_menu[1]} {design_3_i/top_sound_0/inst/dbg_addr_menu[2]} {design_3_i/top_sound_0/inst/dbg_addr_menu[3]} {design_3_i/top_sound_0/inst/dbg_addr_menu[4]} {design_3_i/top_sound_0/inst/dbg_addr_menu[5]} {design_3_i/top_sound_0/inst/dbg_addr_menu[6]} {design_3_i/top_sound_0/inst/dbg_addr_menu[7]} {design_3_i/top_sound_0/inst/dbg_addr_menu[8]} {design_3_i/top_sound_0/inst/dbg_addr_menu[9]} {design_3_i/top_sound_0/inst/dbg_addr_menu[10]} {design_3_i/top_sound_0/inst/dbg_addr_menu[11]} {design_3_i/top_sound_0/inst/dbg_addr_menu[12]} {design_3_i/top_sound_0/inst/dbg_addr_menu[13]} {design_3_i/top_sound_0/inst/dbg_addr_menu[14]} {design_3_i/top_sound_0/inst/dbg_addr_menu[15]}]]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_3_i/top_sound_0/inst/dbg_addr_selected[0]} {design_3_i/top_sound_0/inst/dbg_addr_selected[1]} {design_3_i/top_sound_0/inst/dbg_addr_selected[2]} {design_3_i/top_sound_0/inst/dbg_addr_selected[3]} {design_3_i/top_sound_0/inst/dbg_addr_selected[4]} {design_3_i/top_sound_0/inst/dbg_addr_selected[5]} {design_3_i/top_sound_0/inst/dbg_addr_selected[6]} {design_3_i/top_sound_0/inst/dbg_addr_selected[7]} {design_3_i/top_sound_0/inst/dbg_addr_selected[8]} {design_3_i/top_sound_0/inst/dbg_addr_selected[9]} {design_3_i/top_sound_0/inst/dbg_addr_selected[10]} {design_3_i/top_sound_0/inst/dbg_addr_selected[11]} {design_3_i/top_sound_0/inst/dbg_addr_selected[12]} {design_3_i/top_sound_0/inst/dbg_addr_selected[13]} {design_3_i/top_sound_0/inst/dbg_addr_selected[14]} {design_3_i/top_sound_0/inst/dbg_addr_selected[15]}]]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_3_i/top_sound_0/inst/dbg_loop_music[0]} {design_3_i/top_sound_0/inst/dbg_loop_music[1]} {design_3_i/top_sound_0/inst/dbg_loop_music[2]} {design_3_i/top_sound_0/inst/dbg_loop_music[3]} {design_3_i/top_sound_0/inst/dbg_loop_music[4]} {design_3_i/top_sound_0/inst/dbg_loop_music[5]} {design_3_i/top_sound_0/inst/dbg_loop_music[6]} {design_3_i/top_sound_0/inst/dbg_loop_music[7]} {design_3_i/top_sound_0/inst/dbg_loop_music[8]} {design_3_i/top_sound_0/inst/dbg_loop_music[9]} {design_3_i/top_sound_0/inst/dbg_loop_music[10]} {design_3_i/top_sound_0/inst/dbg_loop_music[11]} {design_3_i/top_sound_0/inst/dbg_loop_music[12]} {design_3_i/top_sound_0/inst/dbg_loop_music[13]} {design_3_i/top_sound_0/inst/dbg_loop_music[14]} {design_3_i/top_sound_0/inst/dbg_loop_music[15]}]]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[0]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[1]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[2]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[3]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[4]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[5]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[6]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[7]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[8]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[9]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[10]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[11]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[12]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[13]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[14]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[15]}]]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[0]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[1]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[2]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[3]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[4]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[5]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[6]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[7]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[8]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[9]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[10]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[11]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[12]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[13]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[14]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[15]}]]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[0]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[1]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[2]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[3]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[4]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[5]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[6]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[7]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[8]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[9]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[10]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[11]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[12]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[13]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[14]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[15]}]]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_arrow_raw]]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_done_arrow]]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_done_combined]]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_done_menu]]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_done_music]]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_menu_raw]]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_music_raw]]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list design_3_i/top_sound_0/inst/dbg_playing_arrow]]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list design_3_i/top_sound_0/inst/dbg_playing_menu]]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list design_3_i/top_sound_0/inst/dbg_playing_music]]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list design_3_i/top_sound_0/inst/dbg_pwm]]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list design_3_i/clk_100MHz_RnM/inst/clk_out2]]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {design_3_i/sync_gen_1_VGA_R[0]} {design_3_i/sync_gen_1_VGA_R[1]} {design_3_i/sync_gen_1_VGA_R[2]} {design_3_i/sync_gen_1_VGA_R[3]}]]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list design_3_i/sync_gen_1_VGA_HSYNC]]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list design_3_i/sync_gen_1_VGA_VSYNC]]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out2]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports gyroscope_enable_0]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports calibrate_0]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports calibration_done_0]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports play_done_0]
set_property src_info {type:XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports o_CS_0]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports o_MOSI_0]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports i_MISO_0]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports o_SCLK_0]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports pwm_out_0]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports aud_sd_0]
set_property src_info {type:XDC file:2 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports uart_rtl_0_rxd]
set_property src_info {type:XDC file:2 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports uart_rtl_0_txd]
