# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_top_sound_0_0/design_3_top_sound_0_0.xci
# IP: The module: 'design_3_top_sound_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_top_sound_0_0/design_3_top_sound_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_top_sound_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_top_sound_0_0/design_3_top_sound_0_0.xci
# IP: The module: 'design_3_top_sound_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_top_sound_0_0/design_3_top_sound_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_top_sound_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
