## Clock signal
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_100MHz]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_100MHz]

## Reset (CPU_RESET)
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports reset_rtl_0]

## VGA Connector Pins
## Red Channel (4 bits)
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {VGA_R[0]}]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {VGA_R[1]}]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {VGA_R[2]}]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {VGA_R[3]}]

## Green Channel (4 bits)
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[0]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {VGA_G[1]}]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[2]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[3]}]

## Blue Channel (4 bits)
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[0]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[1]}]
set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[2]}]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {VGA_B[3]}]

## Sync Signals
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports VGA_HSYNC]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports VGA_VSYNC]

# pushbuttons: L R D C
set_property PACKAGE_PIN P17 [get_ports {gpio_io_i_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[0]}]
set_property PACKAGE_PIN M17 [get_ports {gpio_io_i_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[1]}]
set_property PACKAGE_PIN P18 [get_ports {gpio_io_i_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[2]}]
set_property PACKAGE_PIN N17 [get_ports {gpio_io_i_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[3]}]



set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[5]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[4]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[9]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[9]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[14]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[1]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[4]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[14]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[13]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[8]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[7]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[13]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[15]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[5]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[11]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[10]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[9]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[7]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[11]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[11]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[2]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[1]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[6]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[4]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[3]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[7]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[10]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[10]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[0]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[4]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[1]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[0]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[12]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[15]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[2]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[13]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[6]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[11]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[12]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[10]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[3]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[14]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[5]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[6]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[13]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[3]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[0]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_x[5]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[15]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[8]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[8]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[3]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[15]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[0]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[12]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[2]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_myScore[1]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[2]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[8]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_y[14]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[6]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[7]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[9]}]
set_property MARK_DEBUG true [get_nets {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[12]}]

set_property MARK_DEBUG true [get_nets {design_3_i/gpio_io_i_0[2]}]
set_property MARK_DEBUG true [get_nets {design_3_i/gpio_io_i_0[0]}]
set_property MARK_DEBUG true [get_nets {design_3_i/gpio_io_i_0[1]}]
set_property MARK_DEBUG true [get_nets {design_3_i/gpio_io_i_0[3]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_3_i/clk_100MHz_RnM/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_3_i/framewriter_0/inst/axi_framewriter_y[0]} {design_3_i/framewriter_0/inst/axi_framewriter_y[1]} {design_3_i/framewriter_0/inst/axi_framewriter_y[2]} {design_3_i/framewriter_0/inst/axi_framewriter_y[3]} {design_3_i/framewriter_0/inst/axi_framewriter_y[4]} {design_3_i/framewriter_0/inst/axi_framewriter_y[5]} {design_3_i/framewriter_0/inst/axi_framewriter_y[6]} {design_3_i/framewriter_0/inst/axi_framewriter_y[7]} {design_3_i/framewriter_0/inst/axi_framewriter_y[8]} {design_3_i/framewriter_0/inst/axi_framewriter_y[9]} {design_3_i/framewriter_0/inst/axi_framewriter_y[10]} {design_3_i/framewriter_0/inst/axi_framewriter_y[11]} {design_3_i/framewriter_0/inst/axi_framewriter_y[12]} {design_3_i/framewriter_0/inst/axi_framewriter_y[13]} {design_3_i/framewriter_0/inst/axi_framewriter_y[14]} {design_3_i/framewriter_0/inst/axi_framewriter_y[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_3_i/framewriter_0/inst/axi_framewriter_x[0]} {design_3_i/framewriter_0/inst/axi_framewriter_x[1]} {design_3_i/framewriter_0/inst/axi_framewriter_x[2]} {design_3_i/framewriter_0/inst/axi_framewriter_x[3]} {design_3_i/framewriter_0/inst/axi_framewriter_x[4]} {design_3_i/framewriter_0/inst/axi_framewriter_x[5]} {design_3_i/framewriter_0/inst/axi_framewriter_x[6]} {design_3_i/framewriter_0/inst/axi_framewriter_x[7]} {design_3_i/framewriter_0/inst/axi_framewriter_x[8]} {design_3_i/framewriter_0/inst/axi_framewriter_x[9]} {design_3_i/framewriter_0/inst/axi_framewriter_x[10]} {design_3_i/framewriter_0/inst/axi_framewriter_x[11]} {design_3_i/framewriter_0/inst/axi_framewriter_x[12]} {design_3_i/framewriter_0/inst/axi_framewriter_x[13]} {design_3_i/framewriter_0/inst/axi_framewriter_x[14]} {design_3_i/framewriter_0/inst/axi_framewriter_x[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_3_i/framewriter_0/inst/axi_framewriter_myScore[0]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[1]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[2]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[3]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[4]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[5]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[6]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[7]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[8]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[9]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[10]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[11]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[12]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[13]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[14]} {design_3_i/framewriter_0/inst/axi_framewriter_myScore[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[0]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[1]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[2]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[3]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[4]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[5]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[6]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[7]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[8]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[9]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[10]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[11]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[12]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[13]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[14]} {design_3_i/framewriter_0/inst/axi_framewriter_oppScore[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_3_i/gpio_io_i_0[0]} {design_3_i/gpio_io_i_0[1]} {design_3_i/gpio_io_i_0[2]} {design_3_i/gpio_io_i_0[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_3_i/sync_gen_1_VGA_R[0]} {design_3_i/sync_gen_1_VGA_R[1]} {design_3_i/sync_gen_1_VGA_R[2]} {design_3_i/sync_gen_1_VGA_R[3]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_3_i/clk_100MHz_RnM/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list design_3_i/sync_gen_1_VGA_HSYNC]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list design_3_i/sync_gen_1_VGA_VSYNC]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out2]
