set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports eth_ref_clk]

# add GPIO constraints
# gpio_switches - gpio_io_i_0
set_property PACKAGE_PIN J15 [get_ports {gpio_io_i_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[0]}]
set_property PACKAGE_PIN L16 [get_ports {gpio_io_i_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[1]}]
set_property PACKAGE_PIN M13 [get_ports {gpio_io_i_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[2]}]
set_property PACKAGE_PIN R15 [get_ports {gpio_io_i_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[3]}]
set_property PACKAGE_PIN R17 [get_ports {gpio_io_i_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[4]}]
set_property PACKAGE_PIN T18 [get_ports {gpio_io_i_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[5]}]
set_property PACKAGE_PIN U18 [get_ports {gpio_io_i_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[6]}]
set_property PACKAGE_PIN R13 [get_ports {gpio_io_i_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[7]}]
set_property PACKAGE_PIN T8 [get_ports {gpio_io_i_0[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_io_i_0[8]}]
set_property PACKAGE_PIN U8 [get_ports {gpio_io_i_0[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_io_i_0[9]}]
set_property PACKAGE_PIN R16 [get_ports {gpio_io_i_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[10]}]
set_property PACKAGE_PIN T13 [get_ports {gpio_io_i_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[11]}]
set_property PACKAGE_PIN H6 [get_ports {gpio_io_i_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[12]}]
set_property PACKAGE_PIN U12 [get_ports {gpio_io_i_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[13]}]
set_property PACKAGE_PIN U11 [get_ports {gpio_io_i_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[14]}]
set_property PACKAGE_PIN V10 [get_ports {gpio_io_i_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_0[15]}]

# LED
set_property PACKAGE_PIN H17 [get_ports {gpio_io_o_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[0]}]
set_property PACKAGE_PIN K15 [get_ports {gpio_io_o_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[1]}]
set_property PACKAGE_PIN J13 [get_ports {gpio_io_o_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[2]}]
set_property PACKAGE_PIN N14 [get_ports {gpio_io_o_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[3]}]
set_property PACKAGE_PIN R18 [get_ports {gpio_io_o_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[4]}]
set_property PACKAGE_PIN V17 [get_ports {gpio_io_o_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[5]}]
set_property PACKAGE_PIN U17 [get_ports {gpio_io_o_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[6]}]
set_property PACKAGE_PIN U16 [get_ports {gpio_io_o_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[7]}]
set_property PACKAGE_PIN V16 [get_ports {gpio_io_o_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[8]}]
set_property PACKAGE_PIN T15 [get_ports {gpio_io_o_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[9]}]
set_property PACKAGE_PIN U14 [get_ports {gpio_io_o_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[10]}]
set_property PACKAGE_PIN T16 [get_ports {gpio_io_o_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[11]}]
set_property PACKAGE_PIN V15 [get_ports {gpio_io_o_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[12]}]
set_property PACKAGE_PIN V14 [get_ports {gpio_io_o_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[13]}]
set_property PACKAGE_PIN V12 [get_ports {gpio_io_o_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[14]}]
set_property PACKAGE_PIN V11 [get_ports {gpio_io_o_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_o_0[15]}]


# pushbuttons: L R D C
set_property PACKAGE_PIN P17 [get_ports {gpio_io_i_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_1[0]}]
set_property PACKAGE_PIN M17 [get_ports {gpio_io_i_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_1[1]}]
set_property PACKAGE_PIN P18 [get_ports {gpio_io_i_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_1[2]}]
set_property PACKAGE_PIN N17 [get_ports {gpio_io_i_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_io_i_1[3]}]


