set_property SRC_FILE_INFO {cfile:Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/constrs_1/new/vga_constraints.xdc rfile:../../../local_testing_vga_ip_1.srcs/constrs_1/new/vga_constraints.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/constrs_1/imports/constraints/gyro_nexys_a7.xdc rfile:../../../local_testing_vga_ip_1.srcs/constrs_1/imports/constraints/gyro_nexys_a7.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_100MHz]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports reset_rtl_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {VGA_R[0]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports {VGA_R[1]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {VGA_R[2]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {VGA_R[3]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[0]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {VGA_G[1]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[2]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {VGA_G[3]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[0]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[1]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports {VGA_B[2]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {VGA_B[3]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports VGA_HSYNC]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports VGA_VSYNC]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports btn_start]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports btn_shoot]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports btn_left]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports btn_right]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_clk_out1]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_3_i/clk_100MHz_RnM/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 7 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/seg[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/seg[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/seg[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/seg[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/seg[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/seg[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/seg[6]}]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[6]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[7]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[8]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[9]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[10]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[11]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[12]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[13]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[14]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[15]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[16]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[17]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[18]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[19]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[20]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[21]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[22]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[23]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[24]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[25]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[26]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[27]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[28]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[29]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[30]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_low[31]}]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_char[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_char[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_char[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_char[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_char[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_char[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_char[6]} {design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_char[7]}]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_in[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_in[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_in[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_in[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_in[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_in[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_in[6]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_in[7]}]]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_data[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_data[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_data[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_data[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_data[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_data[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_data[6]} {design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_data[7]}]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[6]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[7]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[8]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[9]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[10]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[11]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[12]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[13]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[14]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[15]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[16]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[17]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[18]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[19]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[20]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[21]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[22]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[23]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[24]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[25]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[26]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[27]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[28]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[29]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[30]} {design_3_i/ps2_keyboard_subsyst_0/inst/char_bitmap_high[31]}]]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_out[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_out[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_out[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_out[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_out[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_out[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_out[6]} {design_3_i/ps2_keyboard_subsyst_0/inst/ascii_out[7]}]]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/addr[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/addr[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/addr[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/addr[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/addr[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/addr[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/addr[6]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/addr[7]}]]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[0]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[1]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[2]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[3]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[4]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[5]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[6]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[7]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[8]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[9]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[10]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[11]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[12]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[13]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[14]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[15]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[16]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[17]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[18]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[19]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[20]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[21]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[22]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[23]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[24]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[25]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[26]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[27]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[28]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[29]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[30]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[31]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[32]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[33]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[34]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[35]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[36]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[37]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[38]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[39]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[40]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[41]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[42]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[43]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[44]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[45]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[46]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[47]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[48]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[49]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[50]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[51]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[52]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[53]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[54]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[55]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[56]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[57]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[58]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[59]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[60]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[61]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[62]} {design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/char_bitmap[63]}]]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_3_i/physics_engine_0/inst/land_x[0]} {design_3_i/physics_engine_0/inst/land_x[1]} {design_3_i/physics_engine_0/inst/land_x[2]} {design_3_i/physics_engine_0/inst/land_x[3]} {design_3_i/physics_engine_0/inst/land_x[4]} {design_3_i/physics_engine_0/inst/land_x[5]} {design_3_i/physics_engine_0/inst/land_x[6]} {design_3_i/physics_engine_0/inst/land_x[7]} {design_3_i/physics_engine_0/inst/land_x[8]}]]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_3_i/physics_engine_0/inst/land_y[0]} {design_3_i/physics_engine_0/inst/land_y[1]} {design_3_i/physics_engine_0/inst/land_y[2]} {design_3_i/physics_engine_0/inst/land_y[3]} {design_3_i/physics_engine_0/inst/land_y[4]} {design_3_i/physics_engine_0/inst/land_y[5]} {design_3_i/physics_engine_0/inst/land_y[6]} {design_3_i/physics_engine_0/inst/land_y[7]}]]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_3_i/top_sound_0/inst/dbg_addr_arrow[0]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[1]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[2]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[3]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[4]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[5]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[6]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[7]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[8]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[9]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[10]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[11]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[12]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[13]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[14]} {design_3_i/top_sound_0/inst/dbg_addr_arrow[15]}]]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_3_i/top_sound_0/inst/dbg_addr_menu[0]} {design_3_i/top_sound_0/inst/dbg_addr_menu[1]} {design_3_i/top_sound_0/inst/dbg_addr_menu[2]} {design_3_i/top_sound_0/inst/dbg_addr_menu[3]} {design_3_i/top_sound_0/inst/dbg_addr_menu[4]} {design_3_i/top_sound_0/inst/dbg_addr_menu[5]} {design_3_i/top_sound_0/inst/dbg_addr_menu[6]} {design_3_i/top_sound_0/inst/dbg_addr_menu[7]} {design_3_i/top_sound_0/inst/dbg_addr_menu[8]} {design_3_i/top_sound_0/inst/dbg_addr_menu[9]} {design_3_i/top_sound_0/inst/dbg_addr_menu[10]} {design_3_i/top_sound_0/inst/dbg_addr_menu[11]} {design_3_i/top_sound_0/inst/dbg_addr_menu[12]} {design_3_i/top_sound_0/inst/dbg_addr_menu[13]} {design_3_i/top_sound_0/inst/dbg_addr_menu[14]} {design_3_i/top_sound_0/inst/dbg_addr_menu[15]}]]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_3_i/top_sound_0/inst/dbg_loop_music[0]} {design_3_i/top_sound_0/inst/dbg_loop_music[1]} {design_3_i/top_sound_0/inst/dbg_loop_music[2]} {design_3_i/top_sound_0/inst/dbg_loop_music[3]} {design_3_i/top_sound_0/inst/dbg_loop_music[4]} {design_3_i/top_sound_0/inst/dbg_loop_music[5]} {design_3_i/top_sound_0/inst/dbg_loop_music[6]} {design_3_i/top_sound_0/inst/dbg_loop_music[7]} {design_3_i/top_sound_0/inst/dbg_loop_music[8]} {design_3_i/top_sound_0/inst/dbg_loop_music[9]} {design_3_i/top_sound_0/inst/dbg_loop_music[10]} {design_3_i/top_sound_0/inst/dbg_loop_music[11]} {design_3_i/top_sound_0/inst/dbg_loop_music[12]} {design_3_i/top_sound_0/inst/dbg_loop_music[13]} {design_3_i/top_sound_0/inst/dbg_loop_music[14]} {design_3_i/top_sound_0/inst/dbg_loop_music[15]}]]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_3_i/top_sound_0/inst/dbg_sample[0]} {design_3_i/top_sound_0/inst/dbg_sample[1]} {design_3_i/top_sound_0/inst/dbg_sample[2]} {design_3_i/top_sound_0/inst/dbg_sample[3]} {design_3_i/top_sound_0/inst/dbg_sample[4]} {design_3_i/top_sound_0/inst/dbg_sample[5]} {design_3_i/top_sound_0/inst/dbg_sample[6]} {design_3_i/top_sound_0/inst/dbg_sample[7]}]]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_3_i/top_sound_0/inst/dbg_loop_menu[0]} {design_3_i/top_sound_0/inst/dbg_loop_menu[1]} {design_3_i/top_sound_0/inst/dbg_loop_menu[2]} {design_3_i/top_sound_0/inst/dbg_loop_menu[3]} {design_3_i/top_sound_0/inst/dbg_loop_menu[4]} {design_3_i/top_sound_0/inst/dbg_loop_menu[5]} {design_3_i/top_sound_0/inst/dbg_loop_menu[6]} {design_3_i/top_sound_0/inst/dbg_loop_menu[7]} {design_3_i/top_sound_0/inst/dbg_loop_menu[8]} {design_3_i/top_sound_0/inst/dbg_loop_menu[9]} {design_3_i/top_sound_0/inst/dbg_loop_menu[10]} {design_3_i/top_sound_0/inst/dbg_loop_menu[11]} {design_3_i/top_sound_0/inst/dbg_loop_menu[12]} {design_3_i/top_sound_0/inst/dbg_loop_menu[13]} {design_3_i/top_sound_0/inst/dbg_loop_menu[14]} {design_3_i/top_sound_0/inst/dbg_loop_menu[15]}]]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_3_i/top_sound_0/inst/dbg_addr_music[0]} {design_3_i/top_sound_0/inst/dbg_addr_music[1]} {design_3_i/top_sound_0/inst/dbg_addr_music[2]} {design_3_i/top_sound_0/inst/dbg_addr_music[3]} {design_3_i/top_sound_0/inst/dbg_addr_music[4]} {design_3_i/top_sound_0/inst/dbg_addr_music[5]} {design_3_i/top_sound_0/inst/dbg_addr_music[6]} {design_3_i/top_sound_0/inst/dbg_addr_music[7]} {design_3_i/top_sound_0/inst/dbg_addr_music[8]} {design_3_i/top_sound_0/inst/dbg_addr_music[9]} {design_3_i/top_sound_0/inst/dbg_addr_music[10]} {design_3_i/top_sound_0/inst/dbg_addr_music[11]} {design_3_i/top_sound_0/inst/dbg_addr_music[12]} {design_3_i/top_sound_0/inst/dbg_addr_music[13]} {design_3_i/top_sound_0/inst/dbg_addr_music[14]} {design_3_i/top_sound_0/inst/dbg_addr_music[15]}]]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_3_i/top_sound_0/inst/dbg_addr_selected[0]} {design_3_i/top_sound_0/inst/dbg_addr_selected[1]} {design_3_i/top_sound_0/inst/dbg_addr_selected[2]} {design_3_i/top_sound_0/inst/dbg_addr_selected[3]} {design_3_i/top_sound_0/inst/dbg_addr_selected[4]} {design_3_i/top_sound_0/inst/dbg_addr_selected[5]} {design_3_i/top_sound_0/inst/dbg_addr_selected[6]} {design_3_i/top_sound_0/inst/dbg_addr_selected[7]} {design_3_i/top_sound_0/inst/dbg_addr_selected[8]} {design_3_i/top_sound_0/inst/dbg_addr_selected[9]} {design_3_i/top_sound_0/inst/dbg_addr_selected[10]} {design_3_i/top_sound_0/inst/dbg_addr_selected[11]} {design_3_i/top_sound_0/inst/dbg_addr_selected[12]} {design_3_i/top_sound_0/inst/dbg_addr_selected[13]} {design_3_i/top_sound_0/inst/dbg_addr_selected[14]} {design_3_i/top_sound_0/inst/dbg_addr_selected[15]}]]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_3_i/top_sound_0/inst/dbg_loop_arrow[0]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[1]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[2]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[3]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[4]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[5]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[6]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[7]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[8]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[9]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[10]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[11]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[12]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[13]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[14]} {design_3_i/top_sound_0/inst/dbg_loop_arrow[15]}]]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[0]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[1]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[2]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[3]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[4]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[5]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[6]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[7]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[8]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[9]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[10]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[11]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[12]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[13]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[14]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/x_axis[15]}]]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[0]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[1]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[2]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[3]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[4]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[5]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[6]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[7]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[8]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[9]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[10]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[11]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[12]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[13]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[14]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/y_axis[15]}]]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[0]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[1]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[2]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[3]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[4]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[5]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[6]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[7]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[8]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[9]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[10]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[11]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[12]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[13]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[14]} {design_3_i/gyro_calc_interface_0/inst/spi_gyroscope_inst/z_axis[15]}]]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[0]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[1]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[2]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[3]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[4]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[5]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[6]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[7]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[8]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[9]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[10]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[11]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[12]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[13]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[14]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[15]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[16]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[17]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[18]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[19]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[20]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[21]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[22]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[23]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[24]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[25]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[26]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[27]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[28]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[29]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[30]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_low[31]}]]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[0]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[1]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[2]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[3]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[4]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[5]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[6]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[7]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[8]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[9]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[10]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[11]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[12]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[13]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[14]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[15]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[16]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[17]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[18]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[19]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[20]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[21]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[22]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[23]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[24]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[25]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[26]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[27]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[28]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[29]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[30]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_x[31]}]]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[0]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[1]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[2]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[3]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[4]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[5]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[6]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[7]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[8]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[9]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[10]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[11]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[12]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[13]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[14]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[15]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[16]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[17]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[18]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[19]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[20]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[21]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[22]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[23]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[24]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[25]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[26]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[27]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[28]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[29]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[30]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_bitmap_high[31]}]]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[0]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[1]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[2]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[3]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[4]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[5]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[6]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[7]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[8]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[9]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[10]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[11]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[12]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[13]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[14]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[15]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[16]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[17]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[18]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[19]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[20]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[21]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[22]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[23]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[24]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[25]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[26]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[27]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[28]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[29]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[30]} {design_3_i/framewriter_0/inst/framewriter_1/axi_char_y[31]}]]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/p1_name[16]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[17]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[18]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[19]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[20]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[21]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[22]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[23]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[24]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[25]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[26]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[27]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[28]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[29]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[30]} {design_3_i/framewriter_0/inst/framewriter_1/p1_name[31]}]]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/p2_chr1[0]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr1[1]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr1[2]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr1[3]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr1[4]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr1[5]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr1[6]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr1[7]}]]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/menu_diff_select[0]} {design_3_i/framewriter_0/inst/framewriter_1/menu_diff_select[1]}]]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/p1_chr1[0]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr1[1]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr1[2]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr1[3]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr1[4]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr1[5]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr1[6]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr1[7]}]]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/p2_chr2[0]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr2[1]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr2[2]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr2[3]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr2[4]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr2[5]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr2[6]} {design_3_i/framewriter_0/inst/framewriter_1/p2_chr2[7]}]]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/p2_name[16]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[17]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[18]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[19]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[20]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[21]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[22]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[23]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[24]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[25]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[26]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[27]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[28]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[29]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[30]} {design_3_i/framewriter_0/inst/framewriter_1/p2_name[31]}]]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe32 [get_nets [list {design_3_i/framewriter_0/inst/framewriter_1/p1_chr2[0]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr2[1]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr2[2]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr2[3]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr2[4]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr2[5]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr2[6]} {design_3_i/framewriter_0/inst/framewriter_1/p1_chr2[7]}]]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe33 [get_nets [list {design_3_i/archery_fsm_0/inst/wind_x_out[0]} {design_3_i/archery_fsm_0/inst/wind_x_out[1]} {design_3_i/archery_fsm_0/inst/wind_x_out[2]} {design_3_i/archery_fsm_0/inst/wind_x_out[3]} {design_3_i/archery_fsm_0/inst/wind_x_out[4]} {design_3_i/archery_fsm_0/inst/wind_x_out[5]} {design_3_i/archery_fsm_0/inst/wind_x_out[6]} {design_3_i/archery_fsm_0/inst/wind_x_out[7]}]]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe34 [get_nets [list {design_3_i/archery_fsm_0/inst/wind_y_out[0]} {design_3_i/archery_fsm_0/inst/wind_y_out[1]} {design_3_i/archery_fsm_0/inst/wind_y_out[2]} {design_3_i/archery_fsm_0/inst/wind_y_out[3]} {design_3_i/archery_fsm_0/inst/wind_y_out[4]} {design_3_i/archery_fsm_0/inst/wind_y_out[5]} {design_3_i/archery_fsm_0/inst/wind_y_out[6]} {design_3_i/archery_fsm_0/inst/wind_y_out[7]}]]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe35 [get_nets [list {design_3_i/archery_fsm_0/inst/difficulty[0]} {design_3_i/archery_fsm_0/inst/difficulty[1]}]]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe36 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_arrow_raw]]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe37 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_done_arrow]]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe38 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_done_combined]]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe39 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_done_menu]]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe40 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_done_music]]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe41 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_menu_raw]]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list design_3_i/top_sound_0/inst/dbg_play_music_raw]]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe43 [get_nets [list design_3_i/top_sound_0/inst/dbg_playing_arrow]]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe44 [get_nets [list design_3_i/top_sound_0/inst/dbg_playing_menu]]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe45 [get_nets [list design_3_i/top_sound_0/inst/dbg_playing_music]]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe46 [get_nets [list design_3_i/top_sound_0/inst/dbg_pwm]]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe47 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/decoder_ascii_valid]]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe48 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/fifo_empty]]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe49 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/fifo_full]]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe50 [get_nets [list design_3_i/physics_engine_0/inst/fire]]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe51 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/get_user_input]]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe52 [get_nets [list design_3_i/framewriter_0/inst/framewriter_1/left_btn]]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe53]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe53 [get_nets [list design_3_i/archery_fsm_0/inst/left_btn]]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe54]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe54 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/ps2_clk]]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe55]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe55]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe55 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/ps2_data]]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe56]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe56]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe56 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/ps2_receiver_valid]]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe57]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe57]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe57 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/read_fifo_en]]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe58]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe58]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe58 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/font_rom_inst/resetn]]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe59]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe59]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe59 [get_nets [list design_3_i/ps2_keyboard_subsyst_0/inst/resetn]]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe60]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe60]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe60 [get_nets [list design_3_i/physics_engine_0/inst/result_valid]]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe61]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe61]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe61 [get_nets [list design_3_i/framewriter_0/inst/framewriter_1/right_btn]]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe62]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe62]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe62 [get_nets [list design_3_i/archery_fsm_0/inst/right_btn]]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe63]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe63]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe63 [get_nets [list design_3_i/archery_fsm_0/inst/shoot_event]]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe64]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe64]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe64 [get_nets [list design_3_i/archery_fsm_0/inst/start_btn]]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list design_3_i/clk_100MHz_RnM/inst/clk_out2]]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {design_3_i/sync_gen_1_VGA_R[0]} {design_3_i/sync_gen_1_VGA_R[1]} {design_3_i/sync_gen_1_VGA_R[2]} {design_3_i/sync_gen_1_VGA_R[3]}]]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list design_3_i/sync_gen_1_VGA_HSYNC]]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list design_3_i/sync_gen_1_VGA_VSYNC]]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out2]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports gyroscope_enable_0]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports calibrate_0]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports reset_fsm]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports calibration_done_0]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports play_done_0]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports get_user_input_0]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { led_ps2_data }]; #IO_L20N_T3_A07_D23_14 Sch=led[14]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V11   IOSTANDARD LVCMOS33 } [get_ports { led_ps2_clk }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {SEG[0]}]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports {SEG[1]}]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {SEG[2]}]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {SEG[3]}]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {SEG[4]}]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {SEG[5]}]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {SEG[6]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {AN[0]}]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {AN[1]}]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {AN[2]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {AN[3]}]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {AN[4]}]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {AN[5]}]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {AN[6]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {AN[7]}]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33} [get_ports o_CS_0]
set_property src_info {type:XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports o_MOSI_0]
set_property src_info {type:XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports i_MISO_0]
set_property src_info {type:XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS33} [get_ports o_SCLK_0]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports ps2_data_0]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports ps2_clk_0]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports pwm_out_0]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports aud_sd_0]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports uart_rtl_0_rxd]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports uart_rtl_0_txd]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {SEG[0]}]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports {SEG[1]}]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {SEG[2]}]
set_property src_info {type:XDC file:2 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {SEG[3]}]
set_property src_info {type:XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {SEG[4]}]
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {SEG[5]}]
set_property src_info {type:XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {SEG[6]}]
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {AN[0]}]
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {AN[1]}]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {AN[2]}]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {AN[3]}]
set_property src_info {type:XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {AN[4]}]
set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {AN[5]}]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {AN[6]}]
set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {AN[7]}]
