@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Mar 14 17:46:16 -0400 2026
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
call xelab  -wto d445a1d20d934d81b9c447cbfed789f2 --incr --debug typical --relax --mt 2 -L lmb_v10_v3_0_9 -L xil_defaultlib -L lmb_bram_if_cntlr_v4_0_15 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_13 -L microblaze_v11_0_0 -L axi_lite_ipif_v3_0_4 -L axi_intc_v4_1_12 -L generic_baseblocks_v2_1_0 -L axi_infrastructure_v1_1_0 -L axi_register_slice_v2_1_18 -L fifo_generator_v13_2_3 -L axi_data_fifo_v2_1_17 -L axi_crossbar_v2_1_19 -L blk_mem_gen_v8_4_2 -L mdm_v3_2_15 -L interrupt_control_v3_1_4 -L axi_gpio_v2_0_20 -L axi_vip_v1_1_4 -L blk_mem_gen_v8_3_6 -L axi_bram_ctrl_v4_1_0 -L xlconcat_v2_1_1 -L axi_protocol_converter_v2_1_18 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb5_behav xil_defaultlib.tb5 xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
