@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 19 15:10:41 -0400 2026
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb5_behav -key {Behavioral:sim_1:Functional:tb5} -tclbatch tb5.tcl -protoinst "protoinst_files/design_3.protoinst" -protoinst "protoinst_files/design_4.protoinst" -protoinst "protoinst_files/design_2.protoinst" -view Y:/vga_project/local_testing_vga_ip_1/tb_sync_generator.wcfg -view Y:/vga_project/local_testing_vga_ip_1/tb_behav_bram.wcfg -view Y:/vga_project/local_testing_vga_ip_1/tb_behav_sync_gen.wcfg -view Y:/vga_project/local_testing_vga_ip_1/tb3_behav_microblaze.wcfg -view Y:/vga_project/local_testing_vga_ip_1/tb5_behav_framewriter_onepixel.wcfg -view Y:/vga_project/local_testing_vga_ip_1/tb5_behav.wcfg -view Y:/vga_project/local_testing_vga_ip_1/tb5_postsynth_functional_sim.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
