# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_pins.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_vip_0_0/design_2_axi_vip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_vip_0_0 || ORIG_REF_NAME==design_2_axi_vip_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_1/design_2_clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1 || ORIG_REF_NAME==design_2_clk_wiz_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_clk_wiz_100M_1/design_2_rst_clk_wiz_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_100M_1 || ORIG_REF_NAME==design_2_rst_clk_wiz_100M_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_0_0/design_2_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_0_bram_0/design_2_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_framewriter_0_0/design_2_framewriter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_framewriter_0_0 || ORIG_REF_NAME==design_2_framewriter_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_sync_gen_1_0/design_2_sync_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_sync_gen_1_0 || ORIG_REF_NAME==design_2_sync_gen_1_0} -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_1/design_2_clk_wiz_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1 || ORIG_REF_NAME==design_2_clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_1/design_2_clk_wiz_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_1 || ORIG_REF_NAME==design_2_clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_1/design_2_clk_wiz_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_rst_clk_wiz_100M_1/design_2_rst_clk_wiz_100M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_100M_1 || ORIG_REF_NAME==design_2_rst_clk_wiz_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_rst_clk_wiz_100M_1/design_2_rst_clk_wiz_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_rst_clk_wiz_100M_1 || ORIG_REF_NAME==design_2_rst_clk_wiz_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_axi_bram_ctrl_0_0/design_2_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_bram_ctrl_0_bram_0/design_2_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_framewriter_0_0/src/vga_pins.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_framewriter_0_0 || ORIG_REF_NAME==design_2_framewriter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_sync_gen_1_0/src/vga_pins.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_sync_gen_1_0 || ORIG_REF_NAME==design_2_sync_gen_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
