# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0.xci
# IP: The module: 'design_3_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0.xci
# IP: The module: 'design_3_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
