# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.cache/wt [current_project]
set_property parent.project_path Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  y:/framewriter_ip
  y:/sync_gen_ip
} [current_project]
update_ip_catalog
set_property ip_output_repo y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files Y:/bram_target.coe
read_verilog -library xil_defaultlib Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/hdl/design_3_wrapper.v
add_files Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/design_3.bd
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_clk_100MHz_0/design_3_clk_100MHz_0_board.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_clk_100MHz_0/design_3_clk_100MHz_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_clk_100MHz_0/design_3_clk_100MHz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_rst_clk_wiz_100M_0/design_3_rst_clk_wiz_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_rst_clk_wiz_100M_0/design_3_rst_clk_wiz_100M_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_rst_clk_wiz_100M_0/design_3_rst_clk_wiz_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_microblaze_0_0/design_3_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_microblaze_0_0/design_3_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_microblaze_0_0/design_3_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_v10_0/design_3_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_ilmb_v10_0/design_3_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_ilmb_v10_0/design_3_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_dlmb_bram_if_cntlr_0/design_3_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_ilmb_bram_if_cntlr_0/design_3_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_lmb_bram_0/design_3_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_xbar_0/design_3_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_microblaze_0_axi_intc_0/design_3_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_microblaze_0_axi_intc_0/design_3_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_microblaze_0_axi_intc_0/design_3_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_mdm_1_0/design_3_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_mdm_1_0/design_3_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_gpio_0_0/design_3_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_gpio_0_0/design_3_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_gpio_0_0/design_3_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_bram_ctrl_1_0/design_3_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_bram_ctrl_1_bram_0/design_3_axi_bram_ctrl_1_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_gpio_1_0/design_3_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_gpio_1_0/design_3_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_gpio_1_0/design_3_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_uartlite_0_0/design_3_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_uartlite_0_0/design_3_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_axi_uartlite_0_0/design_3_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/ip/design_3_auto_pc_0/design_3_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_3/design_3_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/constrs_1/new/vga_constraints.xdc
set_property used_in_implementation false [get_files Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/constrs_1/new/vga_constraints.xdc]

read_xdc Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/constrs_1/imports/constraints/gyro_nexys_a7.xdc
set_property used_in_implementation false [get_files Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/constrs_1/imports/constraints/gyro_nexys_a7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_3_wrapper -part xc7a100tcsg324-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_3_wrapper.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file design_3_wrapper_utilization_synth.rpt -pb design_3_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
