## Clock signal
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_100MHz]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk_100MHz]

## Reset (CPU_RESET)
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports reset_rtl_0]

## UART Interface (RX on PMOD JA PIN 2, TX on PMOD JA PIN 3)
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports uart_rtl_0_rxd]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports uart_rtl_0_txd]

## Switches
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_0_tri_i[0]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_0_tri_i[1]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_0_tri_i[2]}]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_0_tri_i[3]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_0_tri_i[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_0_tri_i[5]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_0_tri_i[6]}]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_0_tri_i[7]}]

## LEDs
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_1_tri_o[0]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_1_tri_o[1]}]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_1_tri_o[2]}]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_1_tri_o[3]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_1_tri_o[4]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_1_tri_o[5]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_1_tri_o[6]}]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {gpio_rtl_1_tri_o[7]}]

set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_0_tri_i[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_0_tri_i[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_0_tri_i[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_0_tri_i[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_0_tri_i[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_0_tri_i[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_0_tri_i[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_0_tri_i[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_1_tri_o[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_1_tri_o[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_1_tri_o[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_1_tri_o[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_1_tri_o[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_1_tri_o[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_1_tri_o[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/gpio_rtl_1_tri_o[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/reset_rtl_0]
set_property MARK_DEBUG true [get_nets design_1_i/uart_rtl_0_rxd]
set_property MARK_DEBUG true [get_nets design_1_i/uart_rtl_0_txd]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/fifo_din[8]}]
set_property MARK_DEBUG false [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/fifo_din[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/fifo_din[7]}]
set_property MARK_DEBUG false [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/fifo_din[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/fifo_din[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/fifo_din[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/fifo_din[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/fifo_din[5]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/tx_DataBits]
set_property MARK_DEBUG true [get_nets design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/tx]
set_property MARK_DEBUG true [get_nets design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/TX0]
set_property MARK_DEBUG true [get_nets design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/serial_Data]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_1/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/gpio_rtl_0_tri_i[0]} {design_1_i/gpio_rtl_0_tri_i[1]} {design_1_i/gpio_rtl_0_tri_i[2]} {design_1_i/gpio_rtl_0_tri_i[3]} {design_1_i/gpio_rtl_0_tri_i[4]} {design_1_i/gpio_rtl_0_tri_i[5]} {design_1_i/gpio_rtl_0_tri_i[6]} {design_1_i/gpio_rtl_0_tri_i[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[0]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[1]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[2]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[3]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[4]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[5]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[6]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_RX_I/out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[0]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[1]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[2]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[3]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[4]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[5]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[6]} {design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/s_axi_wdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/gpio_rtl_1_tri_o[0]} {design_1_i/gpio_rtl_1_tri_o[1]} {design_1_i/gpio_rtl_1_tri_o[2]} {design_1_i/gpio_rtl_1_tri_o[3]} {design_1_i/gpio_rtl_1_tri_o[4]} {design_1_i/gpio_rtl_1_tri_o[5]} {design_1_i/gpio_rtl_1_tri_o[6]} {design_1_i/gpio_rtl_1_tri_o[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/reset_rtl_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/serial_Data]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/TX0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axi_uartlite_0/U0/UARTLITE_CORE_I/UARTLITE_TX_I/tx_DataBits]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/uart_rtl_0_rxd]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/uart_rtl_0_txd]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
