webtalk_init -webtalk_dir Y:\\vga_project\\local_testing_vga_ip_1\\local_testing_vga_ip_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2026-03-15 12:52:23" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ebp0bpbc7dcabprqpusref3u5p" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 6800HS with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.354 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1773588300703" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1773588300703"
webtalk_add_data -client sdk -key uid -value "1773591806544" -context "sdk\\\\bsp/1773591806544"
webtalk_add_data -client sdk -key hwid -value "1772300511411" -context "sdk\\\\bsp/1773591806544"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1773591806544"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1773591806544"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1773591806544"
webtalk_add_data -client sdk -key uid -value "1773591808423" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key hwid -value "1772300511411" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key bspid -value "1773591806544" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key projSize -value "98.62890625" -context "sdk\\\\application/1773591808423"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1773593543581"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1773593543581"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1773593543581"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1773593543581"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1773593543581"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1773593543581"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1773593543581"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1773593543581"
webtalk_transmit -clientid 4173760316 -regid "" -xml Y:\\vga_project\\local_testing_vga_ip_1\\local_testing_vga_ip_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html Y:\\vga_project\\local_testing_vga_ip_1\\local_testing_vga_ip_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm Y:\\vga_project\\local_testing_vga_ip_1\\local_testing_vga_ip_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
