# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_4/ip/design_4_axi_bram_ctrl_0_bram_1/design_4_axi_bram_ctrl_0_bram_1.xci
# IP: The module: 'design_4_axi_bram_ctrl_0_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_4/ip/design_4_axi_bram_ctrl_0_bram_1/design_4_axi_bram_ctrl_0_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_axi_bram_ctrl_0_bram_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: Y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_4/ip/design_4_axi_bram_ctrl_0_bram_1/design_4_axi_bram_ctrl_0_bram_1.xci
# IP: The module: 'design_4_axi_bram_ctrl_0_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/vga_project/local_testing_vga_ip_1/local_testing_vga_ip_1.srcs/sources_1/bd/design_4/ip/design_4_axi_bram_ctrl_0_bram_1/design_4_axi_bram_ctrl_0_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_4_axi_bram_ctrl_0_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
