webtalk_init -webtalk_dir y:/framewriter_ip/managed_ip_project/managed_ip_project.tmp/framewriter_v1_project/framewriter_v1_project.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 19 16:43:23 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "57a47b0f-4210-45f4-8138-4c82ec07cd8e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3a485e37-a0f6-4225-b60d-2d8c64b46448" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 6800HS with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "13631093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13631093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "13631093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Nexys A7 T/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 912339506 -regid "" -xml y:/framewriter_ip/managed_ip_project/managed_ip_project.tmp/framewriter_v1_project/framewriter_v1_project.hw/webtalk/usage_statistics_ext_labtool.xml -html y:/framewriter_ip/managed_ip_project/managed_ip_project.tmp/framewriter_v1_project/framewriter_v1_project.hw/webtalk/usage_statistics_ext_labtool.html -wdm y:/framewriter_ip/managed_ip_project/managed_ip_project.tmp/framewriter_v1_project/framewriter_v1_project.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
